apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: default

images:
- name: goapp
  newName: rampss/argocd
  newTag: f0031f884adbb007c1d197843a7ba8762534b842
